AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Text Analysis Lambda Function

Resources:
  TextAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main
      Runtime: go1.x
      Events:
        AnalyzeAPI:
          Type: Api
          Properties:
            Path: /analyze
            Method: post

Outputs:
  AnalyzeAPIEndpoint:
    Description: "API Gateway endpoint URL for Text Analysis function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze/"